# Project
mod_version=1.1.15
group=org.cyclops.integratedrest
java_version=25

# Common
minecraft_version=26.1.2
mod_name=IntegratedREST
mod_author=rubensworks (aka kroeser)
mod_id=integratedrest
license=MIT
github_url=https://github.com/CyclopsMC/IntegratedREST
issue_tracker_url=https://github.com/CyclopsMC/IntegratedREST/issues
display_url=https://www.curseforge.com/minecraft/mc-mods/integrated-rest
description=Expose Integrated Dynamics networks as a REST API.
fingerprint=bd0353b3e8a2810d60dd584e256e364bc3bedd44

curseforge_project_id=284332
modrinth_project_id=ovubcV3F

# NeoForge
neoforge_version=26.1.2.22-beta
neoforge_loader_version_range=[4,)
neoforge_update_json_url=https://raw.githubusercontent.com/CyclopsMC/Versions/master/neoforge_update/integrated-rest.json

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.caching=true

# Dependencies
cyclopscore_version=1.29.5-1012
integrateddynamics_version=1.32.11-1809
commoncapabilities_version=2.11.4-344
