modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/CyclopsMC/IntegratedREST/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/integrated-rest"
license="MIT"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"
[[mods]]
modId="integratedrest"
version="${file.jarVersion}"
displayName="IntegratedREST"
description='''
Expose Integrated Dynamics networks as a REST API.
'''
[[dependencies.integratedrest]]
    modId="cyclopscore"
    mandatory=true
    versionRange="[1.9.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedrest]]
    modId="commoncapabilities"
    mandatory=true
    versionRange="[2.5.3,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedrest]]
    modId="integrateddynamics"
    mandatory=true
    versionRange="[1.1.16,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedrest]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedrest]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2,]"
    ordering="NONE"
    side="BOTH"
