modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/CyclopsMC/IntegratedREST/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/integrated-rest"
license="MIT"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"
[[mods]]
modId="integratedrest"
version="${file.jarVersion}"
displayName="IntegratedREST"
updateJSONURL="https://raw.githubusercontent.com/CyclopsMC/Versions/master/forge_update/integrated-rest.json"
description='''
Expose Integrated Dynamics networks as a REST API.
'''
[[dependencies.integratedrest]]
    modId="cyclopscore"
    mandatory=true
    versionRange="[1.13.4,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedrest]]
    modId="commoncapabilities"
    mandatory=true
    versionRange="[2.8.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedrest]]
    modId="integrateddynamics"
    mandatory=true
    versionRange="[1.10.13,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedrest]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedrest]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,]"
    ordering="NONE"
    side="BOTH"
