modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/CyclopsMC/IntegratedREST/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/integrated-rest"
license="MIT"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"
[[mods]]
modId="integratedrest"
version="${file.jarVersion}"
displayName="IntegratedREST"
updateJSONURL="https://raw.githubusercontent.com/CyclopsMC/Versions/master/forge_update/integrated-rest.json"
description='''
Expose Integrated Dynamics networks as a REST API.
'''
[[dependencies.integratedrest]]
    modId="cyclopscore"
    type="required"
    versionRange="[1.19.10,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedrest]]
    modId="commoncapabilities"
    type="required"
    versionRange="[2.9.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedrest]]
    modId="integrateddynamics"
    type="required"
    versionRange="[1.23.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedrest]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.integratedrest]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,]"
    ordering="NONE"
    side="BOTH"
